spring:
  application:
    name: auth-service
  profiles:
    active: auth-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: auth_service,config-client

logging:
  level:
    root: info
