spring:
  application:
    name: api-gateway
  profiles:
    active: api-gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      name: api_gateway,config-client

logging:
  level:
    root: info
