spring:
  application:
    name: mail-service
  profiles:
    active: mail-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: mail_service,config-client

logging:
  level:
    root: info
