spring:
  application:
    name: customer-service
  profiles:
    active: customer-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: customer_service,config-client

logging:
  level:
    root: info
