version: '3.8'
services:
  Elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
    networks:
      - ${GLOBAL_NETWORK:-kafka}

  Logstash:
    image: logstash:latest
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - ${GLOBAL_NETWORK:-kafka}

  Kibana:
    image: kibana:latest
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch
    networks:
      - ${GLOBAL_NETWORK:-kafka}
volumes:
  elastic_data: {}

