spring:
  application:
    name: product-service
  profiles:
    active: product-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: product_service,config-client

logging:
  level:
    root: info

#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka-discovery-service:8761/eureka/
