spring:
  application:
    name: order-service
  profiles:
    active: order-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: order_service,config-client

logging:
  level:
    root: info