spring:
  application:
    name: product-service
  profiles:
    active: product-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: product_service,config-client

logging:
  level:
    root: info
