spring:
  application:
    name: product-service
  profiles:
    active: product-service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: product-service,config-client
      uri: http://localhost:8888

logging:
  level:
    root: info
