server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DraganovTs/config-server-boutique-app
          clone-on-start: true
          default-label: master
          search-paths: config-server-boutique-app
      fail-fast: true

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
