eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


name:
  value: nebrass
spring:
  cloud:
    config:
      override-system-properties: false

logstash:
  host: localhost
  port: 5000
  queue-size: 512