server:
  port: 8761

spring:
  application:
    name: eureka-discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    registeredWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka/
