server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/customers/**
        - id: order-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/orders/**
        - id: product-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/products/**