server:
  port: 8999

spring:
  application:
    name: mail-service

management:
  tracing:
    sampling:
      probability: 1.0

kafka:
  bootstrapAddress: localhost:9092
#kafka.bootstrapAddress: localhost:9092