server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DraganovTs/config-server-boutique-app
          default-label: main
          search-paths: config-server-repository
          clone-on-start: true
      fail-fast: true



logging:
  file:
    name: config-server
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG